# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zengziwen/DECODE_ENCODE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zengziwen/build-DECODE_ENCODE-Desktop_Qt_5_10_1_GCC_64bit-Release

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zengziwen/build-DECODE_ENCODE-Desktop_Qt_5_10_1_GCC_64bit-Release/CMakeFiles /home/zengziwen/build-DECODE_ENCODE-Desktop_Qt_5_10_1_GCC_64bit-Release/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zengziwen/build-DECODE_ENCODE-Desktop_Qt_5_10_1_GCC_64bit-Release/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DECODE_ENCODE

# Build rule for target.
DECODE_ENCODE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DECODE_ENCODE
.PHONY : DECODE_ENCODE

# fast build rule for target.
DECODE_ENCODE/fast:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/build
.PHONY : DECODE_ENCODE/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/main.cpp.s
.PHONY : main.cpp.s

svjpeg.o: svjpeg.cpp.o

.PHONY : svjpeg.o

# target to build an object file
svjpeg.cpp.o:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svjpeg.cpp.o
.PHONY : svjpeg.cpp.o

svjpeg.i: svjpeg.cpp.i

.PHONY : svjpeg.i

# target to preprocess a source file
svjpeg.cpp.i:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svjpeg.cpp.i
.PHONY : svjpeg.cpp.i

svjpeg.s: svjpeg.cpp.s

.PHONY : svjpeg.s

# target to generate assembly for a file
svjpeg.cpp.s:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svjpeg.cpp.s
.PHONY : svjpeg.cpp.s

svpng.o: svpng.cpp.o

.PHONY : svpng.o

# target to build an object file
svpng.cpp.o:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svpng.cpp.o
.PHONY : svpng.cpp.o

svpng.i: svpng.cpp.i

.PHONY : svpng.i

# target to preprocess a source file
svpng.cpp.i:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svpng.cpp.i
.PHONY : svpng.cpp.i

svpng.s: svpng.cpp.s

.PHONY : svpng.s

# target to generate assembly for a file
svpng.cpp.s:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/svpng.cpp.s
.PHONY : svpng.cpp.s

toolbox.o: toolbox.cpp.o

.PHONY : toolbox.o

# target to build an object file
toolbox.cpp.o:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/toolbox.cpp.o
.PHONY : toolbox.cpp.o

toolbox.i: toolbox.cpp.i

.PHONY : toolbox.i

# target to preprocess a source file
toolbox.cpp.i:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/toolbox.cpp.i
.PHONY : toolbox.cpp.i

toolbox.s: toolbox.cpp.s

.PHONY : toolbox.s

# target to generate assembly for a file
toolbox.cpp.s:
	$(MAKE) -f CMakeFiles/DECODE_ENCODE.dir/build.make CMakeFiles/DECODE_ENCODE.dir/toolbox.cpp.s
.PHONY : toolbox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... DECODE_ENCODE"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... svjpeg.o"
	@echo "... svjpeg.i"
	@echo "... svjpeg.s"
	@echo "... svpng.o"
	@echo "... svpng.i"
	@echo "... svpng.s"
	@echo "... toolbox.o"
	@echo "... toolbox.i"
	@echo "... toolbox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

